package com.se.pojos;

// Generated Jul 8, 2015 9:10:55 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * MathRuleRelatedFets generated by hbm2java
 */
public class MathRuleRelatedFets implements java.io.Serializable {

	private BigDecimal id;
	private BigDecimal plId;
	private String idFetName;
	private String prefix;
	private BigDecimal value;
	private String updatedFetName;

	public MathRuleRelatedFets() {
	}

	public MathRuleRelatedFets(BigDecimal id, BigDecimal plId,
			String idFetName, String prefix, BigDecimal value) {
		this.id = id;
		this.plId = plId;
		this.idFetName = idFetName;
		this.prefix = prefix;
		this.value = value;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public BigDecimal getPlId() {
		return this.plId;
	}

	public void setPlId(BigDecimal plId) {
		this.plId = plId;
	}

	public String getIdFetName() {
		return this.idFetName;
	}

	public void setIdFetName(String idFetName) {
		this.idFetName = idFetName;
	}

	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}
	
	public String getUpdatedFetName(){
		return updatedFetName;
	}
	
	public void setUpdatedFetName(String updatedFetName){
		this.updatedFetName = updatedFetName;
	}
}
