package com.se.pojos;

// Generated Jul 8, 2015 9:10:55 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ParaRelatedFetsRules generated by hbm2java
 */
public class ParaRelatedFetsRules2 implements java.io.Serializable {

	private BigDecimal id;
	private BigDecimal plId;
	private BigDecimal manId;
	private String fetId;
	private String fetColNm;
	private String fetValId;
	private String updatedFetId;
	private String updatedFetVal;
	private String relation;
	private Date insertionDate;

	public ParaRelatedFetsRules2() {
	}

	public ParaRelatedFetsRules2(BigDecimal id) {
		this.id = id;
	}

	public ParaRelatedFetsRules2(BigDecimal plId, 
			BigDecimal manId, String fetId,
			String fetColNm, String fetValId, String updatedFetId,
			String updatedFetVal, String relation, Date insertionDate) {
		this.plId = plId;
		this.manId = manId;
		this.fetId = fetId;
		this.fetColNm = fetColNm;
		this.fetValId = fetValId;
		this.updatedFetId = updatedFetId;
		this.updatedFetVal = updatedFetVal;
		this.relation = relation;
		this.insertionDate = insertionDate;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public BigDecimal getPlId() {
		return this.plId;
	}

	public void setPlId(BigDecimal plId) {
		this.plId = plId;
	}

	public BigDecimal getManId() {
		return this.manId;
	}

	public void setManId(BigDecimal manId) {
		this.manId = manId;
	}
	public String getFetId() {
		return this.fetId;
	}

	public void setFetId(String fetId) {
		this.fetId = fetId;
	}

	public String getFetColNm() {
		return this.fetColNm;
	}

	public void setFetColNm(String fetIdColNm) {
		this.fetColNm = fetIdColNm;
	}

	public String getFetValId() {
		return this.fetValId;
	}

	public void setFetValId(String fetValId) {
		this.fetValId = fetValId;
	}

	public String getUpdatedFetId() {
		return this.updatedFetId;
	}

	public void setUpdatedFetId(String updatedFetId) {
		this.updatedFetId = updatedFetId;
	}

	public String getUpdatedFetVal() {
		return this.updatedFetVal;
	}

	public void setUpdatedFetVal(String updatedFetVal) {
		this.updatedFetVal = updatedFetVal;
	}
	
	public String getRelation() {
		return this.relation;
	}

	public void setRelation(String relation) {
		this.relation = relation;
	}

	public Date getInsertionDate() {
		return this.insertionDate;
	}

	public void setInsertionDate(Date insertionDate) {
		this.insertionDate = insertionDate;
	}

}
