package com.se.pojos;

// Generated Jul 8, 2015 9:10:55 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ParaMappingRelatedFets generated by hbm2java
 */
public class ParaMappingRelatedFets implements java.io.Serializable {

	private BigDecimal id;
	private BigDecimal plId;
	private String idFetName;
	private String idFetValue;
	private String mappedFetValue;

	public ParaMappingRelatedFets() {
	}

	public ParaMappingRelatedFets(BigDecimal id, BigDecimal plId,
			String idFetName, String idFetValue, String mappedFetValue) {
		this.id = id;
		this.plId = plId;
		this.idFetName = idFetName;
		this.idFetValue = idFetValue;
		this.mappedFetValue = mappedFetValue;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public BigDecimal getPlId() {
		return this.plId;
	}

	public void setPlId(BigDecimal plId) {
		this.plId = plId;
	}

	public String getIdFetName() {
		return this.idFetName;
	}

	public void setIdFetName(String idFetName) {
		this.idFetName = idFetName;
	}

	public String getIdFetValue() {
		return this.idFetValue;
	}

	public void setIdFetValue(String idFetValue) {
		this.idFetValue = idFetValue;
	}

	public String getMappedFetValue() {
		return this.mappedFetValue;
	}

	public void setMappedFetValue(String mappedFetValue) {
		this.mappedFetValue = mappedFetValue;
	}

}
